### ISSUE TITLE
support book and trade persistance whilst running live strategies

### ISSUE THREAD

**Issue by douggie** [timolson/cointrader#109]
currently you need run at least two cointrader instances one in save-date run mode and one in live or paper run mode connecting to the same DB. This means that 2 calls are being made to collect market data for polling exchanges from the same IP, there is a lot of 525 http errors, as too many get requests are being made within a given period.

Rather than slow the rate at which the two instance poll, would it make sense to have a lazy market data persistence mode whilst running in live or paper mode to persist trades and books, to ensure that  only one of get request is done for a given book or trade.

Need to think about how to off load the persistence to a separate thread, tried this before with a blocking queue but had a lot of issues with the entity manager becoming stale.

Ideas welcome on the best approach, not sure if there is anything we can do with c3p0, ehcache and hibernate now it is all in the application stack.

**Comment by timolson** [comment]
JDBC is fundamentally synchronous and blocks on IO, but Hibernate has a `FlushMode` which defaults to `AUTO`, so it will block queries whenever it feels like it and presumably flushes changes in the background.  Currently the `PersistUtilHelper` has `ThreadLocal<EntityManager>`, so the `synchronized` blocks in `PersistUtil.insert()` and `PersistUtil.merge()` should be redundant.  I just removed them (with some other persist cleanup) so if you notice any thread problems... :)

Esper also has nice [threading features](http://esper.codehaus.org/nesper-4.1.0/doc/reference/en/html/api.html#api-threading-advanced), so we could enable _Outbound Threading_ to decouple listeners into separate threads.

Anyway, try just combining all those modules into one `Context` in a new `RunMode`.  I think the current thread model will be ok with Hibernate doing its thing.  Have you actually noticed latency in handling events because of database access?

**Comment by timolson** [comment]
Another thought: one really wants the data-gatherer to be always-on, and to be able to dynamically attach and detach strategies both for testing and live use.  I have in mind a module which exposes events on a port and another module which can connect to an event server and rebroadcast on the local Esper.

**Comment by douggie** [comment]
I tim, nice ideas as always. I have some time next week so will see what I can do. Cointrader now fully thread safe.

**Comment by douggie** [comment]
Hi Tim, do you not feel it would be better to keep keep the mkt data messages in one esper instance rather than putting them up and down the network stack?

In live mode I think we will run with three outbound threads for handeling the strategies, these are all replicas with shared state. 

My thoughts were just to create a persistence thread a bit like how the runnable pump works that just listens to esper events.

P.s there are quite a few redundant sync blocks, just whilst I was making things thread safe and changing data structures. There is quite a bit of tidy up so thanks for persist util!

**Comment by timolson** [comment]
Maybe, maybe not: You might want your strategies in a separate JVM to isolate crashes / memory leaks / whatever from the market data collection.  Also, you can't really "unload" classes from the JVM so even if we implemented dynamic module loading (loading is already done, but unloading is not), the JVM would still have your classes in PermGen space, which may eventually overflow.  This can be mitigated with a JVM flag (HotSpot only) to enable garbage collection in PermGen…
I dunno, I guess it depends on how intense you are about getting 24/7 data and loading/unloading different strategies (or version of the same strat)

**Comment by douggie** [comment]
Hi Tim, I have updated the savedata to run on a espe rate thread so it does not block esper. Longer term you approach is neater as it allows you to persist data for markets that are not part of the strategy. I. Will add another issues for separating the data service from strategies.
