### ISSUE TITLE
Eden space 100% utilised after 6 hours when running paper mode server side

### ISSUE THREAD

**Issue by douggie** [timolson/cointrader#113]
Locally running with the following jvm

Server Restults
root@install:~/paper/tur# java -version
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.5) (7u79-2.5.5-0ubuntu0.14.04.2)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

jstat -gcutil 11113  250 100
  S0     S1     E      O      P     YGC     YGCT    FGC    FGCT     GCT   
  0.00   0.00 100.00  99.99  99.56    504   16.080  7755 8581.009 8597.089
  0.00   0.00 100.00  99.99  99.56    504   16.080  7755 8581.009 8597.089
  0.00   0.00  99.99  99.99  99.56    504   16.080  7756 8582.360 8598.440
  0.00   0.00  99.99  99.99  99.56    504   16.080  7756 8582.360 8598.440
  0.00   0.00  99.99  99.99  99.56    504   16.080  7756 8582.360 8598.440
  0.00   0.00  99.99  99.99  99.56    504   16.080  7756 8582.360 8598.440
  0.00   0.00 100.00  99.99  99.56    504   16.080  7757 8583.426 8599.506
  0.00   0.00 100.00  99.99  99.56    504   16.080  7757 8583.426 8599.506
  0.00   0.00 100.00  99.99  99.56    504   16.080  7757 8583.426 8599.506

Locally
java version "1.7.0_60-ea"
Java(TM) SE Runtime Environment (build 1.7.0_60-ea-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.60-b09, mixed mode)

 jstat -gcutil 37916 250 100
  S0     S1     E      O      P     YGC     YGCT    FGC    FGCT     GCT   
 52.23   0.00  25.45  38.49  99.52     10    0.199     0    0.000    0.199
 52.23   0.00  25.45  38.49  99.52     10    0.199     0    0.000    0.199
 52.23   0.00  25.73  38.49  99.54     10    0.199     0    0.000    0.199
 52.23   0.00  25.73  38.49  99.54     10    0.199     0    0.000    0.199
 52.23   0.00  25.93  38.49  99.54     10    0.199     0    0.000    0.199
 52.23   0.00  25.93  38.49  99.54     10    0.199     0    0.000    0.199
 52.23   0.00  25.93  38.49  99.54     10    0.199     0    0.000    0.199
 52.23   0.00  25.93  38.49  99.54     10    0.199     0    0.000    0.199

**Comment by timolson** [comment]
Are you running with any special VM flags?

**Comment by douggie** [comment]
Hi Tim,


just -Xmx2048M , even if I raise it, it just takes longer.

around 70% of the heap is taken up with book objects, I am creating bars
and just keeping the last book event in the window, so I think it is
something to do with the book.parent causing all the books to be kept in
memory.

Just working through the dump file.

Pretty sure it is the book objects causing the issues.

**Comment by timolson** [comment]
There is a depth to the book parent chain… forget what I set it to.  If you go up enough parents, you will hit a "full" book (not a diff), and that book should have a null parent.  In any case, I wouldn't think this would fill up the eden space since most of those books would have been around for more than one GC cycle and promoted into the survivor heaps.  LMK what you find.

**Comment by timolson** [comment]
Are you sure you want to set the book chain length to 1?  That is going to explode the size of the DB.  Also, it may not address the underlying issue, if there is a leak in eden space.  It might just delay the inevitable?  LMK if you run for a long session and still get problems in eden.

**Comment by timolson** [comment]
One thing which might help is to refactor `BookBuilder` to accept an entire `xchange.OrderBook` instead of adding bids/asks one-by-one.  Adding one-by-one potentially creates many small arrays in eden space as the book grows (if the algo for sizing `ArrayList` doubles when the size limit is reached, then there will be 6 temporary arrays created while resizing up to fit 100 bids or asks).

Another simple solution is to just increase eden space on the command-line with `-XX:MaxNewSize=…` or `-XX:NewRatio=…`  Some people suggest a value of 3 for the new ratio.

**Comment by douggie** [comment]
think I worked it out, think it is the subscription on the savemarketdata, it is keeping all the books in memory as the window is not expiring.

might need to do something like this

  @When("select * from MarketData.std:lastevent()")

If i don't save the data, the eden space is fine.
