### ISSUE TITLE
please integrate ta-lib

### ISSUE THREAD

**Issue by ziggy909** [timolson/cointrader#78]
it's standard and works well

**Comment by timolson** [comment]
Coin Trader would certainly benefit from a library of indicators, but there are a couple issues to consider with ta-lib:

1. ta-lib is batch-oriented while CT is stream-oriented.  The idea of CT is that you can update your indicators incrementally with every trade, book, or tick, which is fast and efficient.  With ta-lib, we would need to keep an array of the entire price history in-memory, and run ta-lib against the entire array whenever new data arrived.  Indicators like Exponential Moving Average do not technically have a cutoff in the past, so additional work is required to define time windows.
  * Esper queries can be used to select all data within the relevant time-windows, but to some extent, this would need to be user-defined.
2. ta-lib assumes fixed time intervals.  This limits its usage to analyzing pre-processed Tick windows, and precludes strategies which can work with variable-interval data.  My personal interest is in realtime-reactive ML strategies which do not use tick windows as input; rather they use raw trades and book events.  So I'm personally not motivated to add ta-lib.
3. ta-lib uses floats and doubles for price data.  This is not horrible, but generally money counts should be handled as integers for absolute precision.  CT uses the Amount classes for perfect precision, and only begrudgingly converts to BigDecimal when necessary.  Altcoins which trade in deep-decimals may have underflow problems in ta-lib, but maybe this is not a big deal for indicators.

It's do-able, but it should probably be based on Tick events selected by an Esper query window.  It won't be the fastest or most memory-efficient, but it would be convenient for many users.

Since it's not relevant to my own trading, someone else will need to lead this work, but I'm happy to help guide the integration.

**Comment by douggie** [comment]
Hi tim,  i have done this in the current build.

Basically the ohlc lib groups esper events into fixed sizes then those can
be used by talib.

**Comment by timolson** [comment]
Douggie, could you write just a quick doc or intro for talib in CT?
Wiki is the best place. Just enough to help get Ziggy started?

**Comment by douggie** [comment]
I meant too!! Hopefully tomorrow am

**Comment by douggie** [comment]
All updaed
